FROM node:12-alpine as build

ARG REACT_APP_SERVICES_HOST=/services/m

WORKDIR /client

COPY ./package.json /client/package.json
COPY ./yarn.lock /client/yarn.lock

RUN yarn install
COPY ./src ./src
COPY ./public ./public
RUN yarn build

FROM nginx
COPY ./nginx/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /client/build /usr/share/nginx/html